[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry]
name = "json-with-comments"
version = "0.0.0"
description = "JSON with Comments for Python"
license = "MIT"
authors = ["Takumasa Nakamura <n.takumasa@gmail.com>"]
readme = "README.md"
repository = "https://github.com/n-takumasa/json-with-comments"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [
    { include = "jsonc" },
]

[tool.poetry.dependencies]
python = ">=3.7, <3.13"

[tool.poetry.group.dev.dependencies]
pytest = "*"
tox = ">=3.27,<5.0"
tomli = { version = "^2.0.1", python = "<3.11" }
